# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-31 02:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=80, verbose_name='company name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('gender', models.CharField(blank=True, choices=[('f', 'Mme'), ('m', 'M')], max_length=1, verbose_name='gender')),
                ('siret_number', models.CharField(blank=True, max_length=80, verbose_name='siret number')),
                ('status', models.CharField(choices=[('a', 'Public'), ('b', 'Professional')], max_length=1, verbose_name='status')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated_on')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
