# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-01 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180531_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=3, default=0.055, max_digits=5, verbose_name='vat percentage'),
        ),
    ]
