# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 04:49
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models
import geoposition.fields
import product.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180718_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='image',
            field=models.FileField(blank=True, default='', upload_to=product.utils.product_upload_to, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productextra',
            name='background_image',
            field=models.ImageField(blank=True, default='', upload_to=product.utils.product_upload_to, verbose_name='background image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productextra',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, default='', verbose_name='color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productextra',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=product.utils.product_upload_to, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productextra',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, default='', max_length=42, verbose_name='origin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productextra',
            name='song',
            field=models.FileField(blank=True, default='', upload_to=product.utils.product_upload_to, verbose_name='track file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productlang',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productlang',
            name='description_short',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='description short 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productlang',
            name='description_short2',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='description short 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productlang',
            name='description_short3',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='description short 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productlang',
            name='meta_description',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='meta description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productlang',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='meta title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variation',
            name='ean13',
            field=models.CharField(blank=True, default='', max_length=13, verbose_name='ean13'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variation',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=product.utils.product_upload_to, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variation',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='reference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variation',
            name='supplier_reference',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='supplier reference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variation',
            name='upc',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='upc'),
            preserve_default=False,
        ),
    ]
