# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_auto_20180531_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicenumber',
            name='last_used_number',
            field=models.CharField(default='', editable=False, max_length=20, verbose_name='last used number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='order id'),
            preserve_default=False,
        ),
    ]
